{
'name': 'maryam_RACHID',
'summary': "Maryam RACHID",
'description': """
        Projet : Gestion de stock
        """,
  'author': "Maryam RACHID",
  'website': "",
  'category': 'Uncategorized',
  'version': '1.0',
  'sequence':0,
   'depends': [],
   'data': ['views/bon.xml',
            'views/compte.xml',
            'views/demande.xml',
            'views/employee.xml',
            'views/entreprise.xml',
            'views/ficheMvt.xml',
            'views/fournisseur.xml',
            'views/magasinier.xml',
            'views/product.xml',
            'views/responsableStock.xml',
            'views/stock.xml',
            'views/role.xml',
            'security/groups.xml'
   ],
   'demo': [],
   'installable': True,
   'application': True,
   'license': '',
}